/**
 * `npx designerpunk sync` — reconcile what DesignerPunk manages in a consumer
 * repo with the installed package, and report (never write) everything else.
 *
 * Spec 123 Task 5 (design.md § "C7"; Reqs 5.1, 5.2, 5.5–5.8). Re-scoped from
 * Spec 111 under Model B:
 *  - **Ours never flows into theirs.** The token tier (`src/tokens`), `src/types`
 *    and the pre-123 component copies are NOT managed: never scanned for
 *    reconciliation, never written (Req 5.8). Their old manifest entries are
 *    PRUNED with a one-line report per group.
 *  - **What is managed is what the manifest recorded** — since Task 16.5: the
 *    GENERATED surfaces (`origin: 'generated'`; the agent layer at file grain,
 *    the `CLAUDE.md` region at region grain) for the manifest's
 *    `attachedTargets`, whose package side is freshly generated by
 *    `emitConsumer` (C7, C20), and the MCP keys (`grain: 'key'`). The release-1
 *    package copies (`origin: 'copy'` under `COPY_ROOTS`) are NOT managed: they
 *    are LEGACY COPIES, reported, and offered `--migrate-legacy` only together
 *    with the attach step (C7 Migration item 4).
 *  - **No class applies without the report first.** Off a terminal, nothing is
 *    written without `--apply`; on a terminal, one batch confirmation. A
 *    `conflict` applies only with `--overwrite <path>`, a `deleted-by-you` only
 *    with `--restore <path>`.
 *
 * Order: resolve → steward guard → manifest (load | relocate legacy) → prune →
 * classify (generated files + regions, keys) → legacy copies → migration →
 * repairs → REPORT → decide → (--migrate-legacy: removal, then attach) → apply →
 * save.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { resolvePackage } from './PackageResolver';
import { scanFiles } from './FileScanner';
import {
  loadManifest,
  loadLegacyManifest,
  saveManifest,
  convertLegacyManifest,
  pruneDemanaged,
  pruneReportLines,
  writeLegacyPointer,
  legacyHasPointer,
  MANIFEST_FILE,
  LEGACY_MANIFEST_PATH,
  MANIFEST_SCHEMA_VERSION,
} from './Manifest';
import type { DesignerPunkManifest, PrunedGroup } from './Manifest';
import { loadIgnoreFilter } from './IgnoreFilter';
import type { IgnoreFilter } from './IgnoreFilter';
import { classifyFiles, classifyRegion, emptyClassification, regionEntryId } from './Classifier';
import type { ClassificationResult, ClassifiedFile } from './Classifier';
import type { ScannedFile } from './FileScanner';
import { hashBuffer } from './FileScanner';
import type { HarnessTarget, ManifestEntry } from './Manifest';
import {
  regionMarkers,
  spliceRegion,
  appendRegion,
  wrapRegion,
  normalizeRegionContent,
  CLAUDE_MD_COMMENT,
  GITIGNORE_COMMENT,
} from './RegionGrain';
import {
  managedRegionMarkersMissingMessage,
  managedRegionEditedInsideMessage,
  restartLineSequencedMessage,
  gitignoreBlockOfferMessage,
  gitignoreBlockReportMessage,
  gitignoreBlockConfigUnreadableMessage,
  gitignoreBlockAddedMessage,
} from '../shared/errorCatalog';
import {
  GITIGNORE_FILE,
  GITIGNORE_REGION_ID,
  GITIGNORE_MARKERS,
  computeGitignoreRegion,
  applyGitignoreRegion,
  hasGitignoreBlock,
  designerpunkDirIgnoreState,
} from '../shared/gitignoreRegion';
import { confirmGitignoreBlock } from './Prompter';
import { emitAgentLayer, resolveAgentTarget, attachRefusal, REFERENCE_SERVERS } from '../attach';
import {
  KEY_SURFACES,
  computePackageKeys,
  readProjectKeys,
  classifySurfaceKeys,
} from './KeyGrain';
import type { SurfaceKeyResult } from './KeyGrain';
import {
  buildReport,
  displayReport,
  STEWARD_REPO_MESSAGE,
  OFF_TTY_REPORT_ONLY_MESSAGE,
  RETIRED_FORCE_MESSAGE,
  corruptManifestMessage,
  packageKeysUnavailableMessage,
  untrackedNewMessage,
} from './Reporter';
import { applyKeys } from './Applier';
import { reportAndMaybeFixStaleSteeringDir } from './SteeringDirCheck';
import {
  migrationTrigger,
  hasLegacyCopies,
  assessComponentCopies,
  resolveUpperBound,
  migrationReportLines,
  relocateComponents,
  npmRailFetcher,
  repairOffers,
  repairRegistryPin,
  repairTsconfigPins,
  assessLegacyCopies,
  legacyCopyReportLines,
  removeLegacyCopies,
  legacyRemovalSummary,
  migrateLegacyNeedsTargetMessage,
  migrateLegacyRefusedMessage,
} from './Migration';
import type { MigrationAssessment, PackageFetcher, RelocationResult, AttachAvailability, LegacyCopyAssessment, LegacyRemoval } from './Migration';
import {
  loadNameContract,
  readPresentNames,
  checkNameContract,
  contractMissingMessage,
  assessTypeContract,
  previousContractAt,
  configUnreadableMessage,
} from './NameContract';
import type { NameContractResult, TypeContractOutcome } from './NameContract';
import { loadConfig } from '../../config/ConfigLoader';
import type { ConfigModuleLoader } from '../../config/ConfigLoader';

export interface SyncOptions {
  projectRoot: string;
  /** Report only; never write (any TTY state). */
  dryRun?: boolean;
  /** Apply updates without the terminal confirmation (the off-TTY path). */
  apply?: boolean;
  /** `deleted-by-you` paths (or `<file>#<key>` ids) to re-add. */
  restore?: string[];
  /** `conflict` paths (or `<file>#<key>` ids) to overwrite. */
  overwrite?: string[];
  /** The retired `--force` / `--accept-all` flags were passed (reported, not honored). */
  retiredForce?: boolean;
  /** Test seam — defaults to `process.stdin.isTTY`. */
  isTTY?: boolean;
  /** Test seam — the terminal batch confirmation. */
  confirm?: (question: string) => Promise<boolean>;
  /** Test seam — the `.gitignore` block offer's own `[y/N]` question (default No; PR-9). */
  confirmGitignoreBlock?: (question: string) => Promise<boolean>;
  /** `--migrate-components`: relocate forks to src/components/<Name>/, remove unmodified copies. */
  migrateComponents?: boolean;
  /** Test seam — the migration's package fetcher (default: the consumer's own npm rail). */
  fetcher?: PackageFetcher;
  /** `--repair-npmrc`: remove the `@3fn` → GitHub Packages mapping line (Req 5.1). */
  repairNpmrc?: boolean;
  /** `--repair-tsconfig`: remove tsconfig.test.json's raw-src re-pins (Req 5.2). */
  repairTsconfig?: boolean;
  /** Test seam — the config-module loader for the name contract's output directory (Task 6). */
  configLoader?: ConfigModuleLoader;
  /**
   * `--migrate-legacy` (C7 Migration item 4; Task 16.5): remove the release-1 legacy copies, then — in the
   * same run — attach the agent layer. Offered and honored ONLY when attach is available.
   */
  migrateLegacy?: boolean;
  /** `--target=<t>` (repeatable): the target(s) `--migrate-legacy`'s attach step adds beside the manifest's `attachedTargets`. */
  targets?: string[];
  /**
   * Test seam — the package side of the generated surfaces (default: the installed package's
   * `dist/generator/consumer-entry.js`, `emitConsumer` in `mode: 'sync'`). `null` = unavailable.
   */
  agentLayer?: AgentLayerSource | null;
}

/** One file the package's agent-layer lane emits (C20's `emitConsumer` file list). */
export interface EmittedAgentFile {
  path: string;
  content: string;
  grain: 'file' | 'region';
}

/** The package side of the generated surfaces (C7: "freshly generated, by `emitConsumer`"). */
export interface AgentLayerSource {
  /** The packaged profile's declared targets (C12's single list — never a literal here). */
  declaredTargets(): readonly string[];
  emit(target: string): Promise<{ files: EmittedAgentFile[]; warnings: string[] }>;
}

/** The default source: the installed package's own compiled lane. Throws (the reason) when it cannot load. */
function bundleAgentLayerSource(pkgRoot: string, projectRoot: string): AgentLayerSource {
  const { entry, profile } = resolveAgentTarget(pkgRoot, undefined, 'sync');
  return {
    declaredTargets: () => profile.targets,
    emit: async (target) => {
      const r = await entry.emitConsumer({ packageRoot: pkgRoot, consumerRoot: projectRoot, target, mode: 'sync' });
      return { files: r.files, warnings: r.warnings };
    },
  };
}

export interface SyncOutcome {
  /** Why the run ended early, if it did. */
  stopped?: 'steward' | 'corrupt-manifest' | 'dry-run' | 'off-tty' | 'declined';
  applied: string[];
  manifestWritten: boolean;
  report: string[];
  /** The migration assessment, when the pre-123 surface triggered it. */
  migration?: MigrationAssessment;
  relocation?: RelocationResult;
  /** Ordered events (fetches, repair offers) — the ordering instrument (C7 step 6). */
  trace: string[];
  /** The name-contract check (Req 5A) — report only, never a write. */
  nameContract?: NameContractResult | { status: 'cannot-check'; lines: string[] };
  /** The type contract (DD11; fork-1 ruling B) — report only; the hash is re-recorded only when the manifest is written. */
  typeContract?: TypeContractOutcome;
  /** The release-1 legacy copies (C7 Migration item 4), when the manifest records any. */
  legacyCopies?: LegacyCopyAssessment;
  /** Whether `--migrate-legacy` was offered — only ever when attach is available. */
  attach?: AttachAvailability;
  /** What `--migrate-legacy` removed (its attach step's targets are in `trace`). */
  legacyRemoval?: LegacyRemoval;
  /** The generated-surface classification (file + region grain), when computed. */
  generated?: GeneratedSurfaces;
  /**
   * The `.gitignore` block's offer (PR-9), when the repo was born without one and git is not ignoring
   * `.designerpunk/`: `added` (a yes), `declined` (No or Enter), `reported` (nobody could answer — off a
   * terminal, `--apply` included, or `--dry-run`: the report row was printed and nothing was written).
   * Absent when no offer applied.
   */
  gitignoreBlock?: 'added' | 'declined' | 'reported';
}

/** Parse `sync`'s CLI flags (everything after `sync`). */
export function parseSyncArgs(argv: string[]): Omit<SyncOptions, 'projectRoot'> {
  const opts: Omit<SyncOptions, 'projectRoot'> = { restore: [], overwrite: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--apply') opts.apply = true;
    else if (a === '--force' || a === '--accept-all') opts.retiredForce = true;
    else if (a === '--restore' && argv[i + 1]) opts.restore!.push(argv[++i]);
    else if (a.startsWith('--restore=')) opts.restore!.push(a.slice('--restore='.length));
    else if (a === '--overwrite' && argv[i + 1]) opts.overwrite!.push(argv[++i]);
    else if (a.startsWith('--overwrite=')) opts.overwrite!.push(a.slice('--overwrite='.length));
    else if (a === '--migrate-components') opts.migrateComponents = true;
    else if (a === '--repair-npmrc') opts.repairNpmrc = true;
    else if (a === '--repair-tsconfig') opts.repairTsconfig = true;
    else if (a === '--migrate-legacy') opts.migrateLegacy = true;
    else if (a === '--target' && argv[i + 1]) (opts.targets ??= []).push(argv[++i]);
    else if (a.startsWith('--target=')) (opts.targets ??= []).push(a.slice('--target='.length));
  }
  return opts;
}

function realpathOr(p: string): string {
  try {
    return fs.realpathSync(p);
  } catch {
    return path.resolve(p);
  }
}

async function terminalConfirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answer = await new Promise<string>((resolve) => rl.question(`${question} [y/N]: `, resolve));
  rl.close();
  return answer.trim().toLowerCase() === 'y' || answer.trim().toLowerCase() === 'yes';
}

/**
 * `sync`, then the `.gitignore` block's offer (PR-9). The offer is its OWN question, asked after
 * `sync`'s report and its batch confirmation, so it runs after the main flow whichever way that
 * ended (nothing to apply, applied, declined); it never runs for a steward repo or a corrupt manifest.
 */
export async function runSync(options: SyncOptions): Promise<SyncOutcome> {
  const outcome = await runSyncMain(options);
  if (outcome.stopped === 'steward' || outcome.stopped === 'corrupt-manifest') return outcome;
  const offered = await offerGitignoreBlock(options, outcome);
  if (offered) outcome.gitignoreBlock = offered;
  return outcome;
}

/**
 * The `.gitignore` block's offer for a repo born on 15.0.0, which has none (design.md C24, PR-9 erratum).
 *  - Only a born-posture manifest that records no block, with no markers in the file, and with the file
 *    not listed in `.designerpunkignore`.
 *  - **Detected by effect**: only when `git check-ignore -q .designerpunk/` exits 1. Exit 0 (already ignored),
 *    exit 128 (not a git repository, or an error) and `git` off PATH print nothing and write nothing.
 *  - Nobody can answer (off a terminal — `--apply` included — or `--dry-run`): the report row is printed,
 *    nothing is written.
 *  - Otherwise its own `[y/N]`, default No: only an explicit yes writes the block. A No writes nothing and
 *    is asked again on the next interactive `sync`.
 */
async function offerGitignoreBlock(options: SyncOptions, outcome: SyncOutcome): Promise<SyncOutcome['gitignoreBlock'] | undefined> {
  const { projectRoot } = options;
  const loaded = loadManifest(projectRoot);
  if (loaded.kind !== 'ok') return undefined;
  const manifest = loaded.manifest;
  if (manifest.posture !== 'born') return undefined;
  if (Object.prototype.hasOwnProperty.call(manifest.entries, GITIGNORE_REGION_ID)) return undefined;
  if (loadIgnoreFilter(projectRoot).isIgnored(GITIGNORE_FILE)) return undefined;
  if (hasGitignoreBlock(projectRoot)) return undefined;
  if (designerpunkDirIgnoreState(projectRoot) !== 'not-ignored') return undefined;

  const isTTY = options.isTTY ?? Boolean(process.stdin.isTTY);
  if (options.dryRun || !isTTY) {
    console.log(`\n⚠️  ${gitignoreBlockReportMessage()}`);
    return 'reported';
  }
  const computed = await computeGitignoreRegion(projectRoot, options.configLoader);
  if (!computed.ok) {
    console.log(`\n⚠️  ${gitignoreBlockConfigUnreadableMessage(computed.reason)}`);
    return undefined;
  }
  const ask = options.confirmGitignoreBlock ?? ((q: string) => confirmGitignoreBlock(q));
  if (!(await ask(gitignoreBlockOfferMessage()))) return 'declined';
  const applied = applyGitignoreRegion(projectRoot, computed.content, manifest.entries);
  if (applied.outcome === 'collision') {
    console.log(`  ⚠️  ${applied.message}`);
    return undefined;
  }
  if (saveManifest(projectRoot, manifest)) outcome.manifestWritten = true;
  outcome.applied.push(GITIGNORE_REGION_ID);
  console.log(`  ✓ ${gitignoreBlockAddedMessage()}`);
  return 'added';
}

async function runSyncMain(options: SyncOptions): Promise<SyncOutcome> {
  const { projectRoot } = options;
  const outcome: SyncOutcome = { applied: [], manifestWritten: false, report: [], trace: [] };
  const isTTY = options.isTTY ?? Boolean(process.stdin.isTTY);

  // 1. Resolve the installed package.
  const pkg = resolvePackage(projectRoot);

  // 1b. Steward exemption (design C2; found-not-fixed item 5): the package's own
  //     tree is not a consumer. Nothing is read or written — including this
  //     repo's own stale `.kiro/sync-manifest.json`, which sync does not own here.
  if (realpathOr(pkg.root) === realpathOr(projectRoot)) {
    console.log(STEWARD_REPO_MESSAGE);
    return { ...outcome, stopped: 'steward', report: [STEWARD_REPO_MESSAGE] };
  }
  console.log(`📦 @3fn/core v${pkg.version}\n`);
  if (options.retiredForce) console.log(`${RETIRED_FORCE_MESSAGE}\n`);

  // 2. Manifest — the root manifest, else the legacy one (relocated on apply).
  const manifestLines: string[] = [];
  const loaded = loadManifest(projectRoot);
  if (loaded.kind === 'corrupt') {
    const msg = corruptManifestMessage(loaded.error);
    console.log(msg);
    return { ...outcome, stopped: 'corrupt-manifest', report: [msg] };
  }
  let manifest: DesignerPunkManifest;
  let pruned: PrunedGroup[] = [];
  let relocateLegacy = false;
  let persistManifest: boolean;
  if (loaded.kind === 'ok') {
    manifest = loaded.manifest;
    persistManifest = true;
  } else {
    const legacy = loadLegacyManifest(projectRoot);
    if (legacy) {
      const conv = convertLegacyManifest(legacy, pkg.version);
      manifest = conv.manifest;
      pruned = conv.pruned;
      relocateLegacy = true;
      persistManifest = true;
      manifestLines.push(
        `found the pre-123 manifest ${LEGACY_MANIFEST_PATH} (last synced at ${legacy.version}) — it moves to ${MANIFEST_FILE} at the repo root when changes apply`,
      );
    } else {
      manifest = {
        version: MANIFEST_SCHEMA_VERSION,
        posture: 'born',
        installedVersion: pkg.version,
        contractHash: '',
        attachedTargets: [],
        entries: {},
      };
      persistManifest = false;
      manifestLines.push(`no ${MANIFEST_FILE} and no ${LEGACY_MANIFEST_PATH} — nothing here was recorded as DesignerPunk's, so nothing is managed`);
    }
  }
  const entries = manifest.entries;
  pruned = [...pruned, ...pruneDemanaged(entries)];
  manifestLines.push(...pruneReportLines(pruned));

  // 3. The agent-layer source (C20) — the package side of the generated surfaces, and the
  //    availability of the attach step `--migrate-legacy` runs. Loaded once.
  let agentLayer: AgentLayerSource | null = null;
  let agentLayerReason = '';
  if (options.agentLayer !== undefined) {
    agentLayer = options.agentLayer;
    if (!agentLayer) agentLayerReason = 'the agent-layer lane is unavailable';
  } else {
    try {
      agentLayer = bundleAgentLayerSource(pkg.root, projectRoot);
    } catch (err) {
      agentLayerReason = (err as Error).message;
    }
  }
  const emissions = new Map<string, Promise<{ files: EmittedAgentFile[]; warnings: string[] }>>();
  const emitFor = (target: string) => {
    if (!emissions.has(target)) emissions.set(target, agentLayer!.emit(target));
    return emissions.get(target)!;
  };

  // 3b. Generated surfaces (C7 rows ADDED) — file and region grain, for attachedTargets ONLY.
  const ignore = loadIgnoreFilter(projectRoot);
  const sections: Array<{ title: string; lines: string[] }> = [];
  let files: ClassificationResult = emptyClassification();
  if (manifest.attachedTargets.length > 0) {
    if (!agentLayer) {
      sections.push({ title: '⚠️  Generated agent layer:', lines: [agentLayerUnavailableMessage(agentLayerReason)] });
    } else {
      try {
        outcome.generated = await classifyGenerated(projectRoot, manifest.attachedTargets, emitFor, entries, ignore);
        files = outcome.generated.files;
        const g = outcome.generated;
        const lines: string[] = [
          ...g.warnings.map((w) => `⚠️  ${w}`),
          ...g.markersMissing.map((f) => managedRegionMarkersMissingMessage(f)),
          ...g.untrackedNew.map((u) => untrackedNewMessage(u.path, u.target)),
        ];
        if (lines.length > 0) sections.push({ title: '🧩 Generated agent layer:', lines });
      } catch (err) {
        sections.push({ title: '⚠️  Generated agent layer:', lines: [agentLayerUnavailableMessage((err as Error).message)] });
      }
    }
  }

  // 4. Key grain — the package side for every target whose keys the manifest records (attachedTargets,
  //    plus a target MCP-wired without its agent layer: `init --skip-agents`, `attach --reference`).
  //    A consume-posture manifest's package side is the reference scope (docs + application only, C20).
  const keyResults: SurfaceKeyResult[] = [];
  const keyTargets = keyGrainTargets(manifest);
  if (keyTargets.length > 0) {
    const pkgKeys = computePackageKeys(pkg.root, keyTargets);
    if (pkgKeys.kind === 'unavailable') {
      sections.push({ title: '⚠️  MCP configuration:', lines: [packageKeysUnavailableMessage(pkgKeys.reason)] });
    } else {
      if (manifest.posture === 'consume') restrictToReference(pkgKeys.keys);
      for (const surface of KEY_SURFACES) {
        const pkgSurfaceKeys = pkgKeys.keys.get(surface.file);
        if (!pkgSurfaceKeys) continue;
        keyResults.push(classifySurfaceKeys(surface, pkgSurfaceKeys, readProjectKeys(projectRoot, surface), entries));
      }
    }
  }

  // 4a. The `.gitignore` block (C24; Task 20.2) — TARGET-FREE. Classified from its own source
  //     (`shared/gitignoreRegion.ts`, computed from `loadConfig(...).outputDir`), never from
  //     `emitConsumer`'s per-target output, which sees per-target regions only (`classifyGenerated`). Only a
  //     block the manifest already records is reconciled here; the first-time offer is `offerGitignoreBlock`.
  //     The id `.gitignore#managed` then flows through the same report and apply rules as any region.
  const gitignoreContents = new Map<string, string>();
  const giEntry = entries[GITIGNORE_REGION_ID];
  if (giEntry && giEntry.origin === 'generated' && giEntry.grain === 'region' && !ignore.isIgnored(GITIGNORE_FILE)) {
    const computed = await computeGitignoreRegion(projectRoot, options.configLoader);
    if (!computed.ok) {
      sections.push({ title: '⚠️  .gitignore block:', lines: [gitignoreBlockConfigUnreadableMessage(computed.reason)] });
    } else {
      const abs = path.join(projectRoot, GITIGNORE_FILE);
      const text = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf-8') : undefined;
      const c = classifyRegion(text, GITIGNORE_MARKERS, computed.content, giEntry, false);
      const item = (classification: ClassifiedFile['classification'], reason?: string): ClassifiedFile => ({
        relativePath: GITIGNORE_REGION_ID,
        classification,
        packageHash: hashBuffer(normalizeRegionContent(computed.content)),
        manifestHash: giEntry.hash,
        ...(reason ? { reason } : {}),
      });
      gitignoreContents.set(GITIGNORE_REGION_ID, computed.content);
      switch (c.kind) {
        case 'unchanged': files.unchanged.push(item('unchanged')); break;
        case 'updated-safe': files.updatedSafe.push(item('updated-safe', 'unchanged by you — package updated')); break;
        case 'conflict': files.conflicts.push(item('conflict', managedRegionEditedInsideMessage(GITIGNORE_FILE))); break;
        case 'deleted-by-you': files.deletedByYou.push(item('deleted-by-you')); break;
        case 'markers-missing':
          sections.push({ title: '🧩 .gitignore block:', lines: [managedRegionMarkersMissingMessage(GITIGNORE_FILE)] });
          break;
        default: break; // new / untracked-new / adoptable cannot arise for a recorded entry
      }
    }
  }

  // 4b. Legacy copies (C7 Migration item 4) — keyed on `origin: 'copy'` under the release-1 copy roots,
  //     never on the manifest's version. REPORTED; `--migrate-legacy` is offered ONLY when the attach
  //     step is available, and runs it in the same flow.
  const legacy = assessLegacyCopies(projectRoot, entries);
  if (legacy) {
    outcome.legacyCopies = legacy;
    outcome.attach = await attachAvailability(projectRoot, manifest, options.targets ?? [], agentLayer, agentLayerReason, emitFor);
    sections.push({ title: '🧳 Legacy copies from an earlier init:', lines: legacyCopyReportLines(legacy, outcome.attach) });
  }

  // 5. Migration — pre-123 component copies (C7 steps 2–5), judged against shipped content.
  const trigger = migrationTrigger(projectRoot, relocateLegacy);
  if (trigger) {
    const lines: string[] = [];
    if (hasLegacyCopies(projectRoot)) {
      const fetcher = options.fetcher ?? npmRailFetcher(projectRoot);
      try {
        const upperBound = resolveUpperBound(projectRoot, loaded.kind === 'ok' ? manifest.installedVersion : null);
        outcome.migration = assessComponentCopies(projectRoot, { fetcher, upperBound, trigger });
      } finally {
        fetcher.dispose?.();
      }
      for (const v of outcome.migration.fetchLog) outcome.trace.push(`fetch:${v}`);
      lines.push(...migrationReportLines(outcome.migration));
    }
    sections.push({ title: '🧬 Migrating from a pre-123 install:', lines });
  }

  // 6. Repairs (C7 step 6) — OFFERED only now, after the migration fetch ran
  //    through the consumer's rail (the npmrc repair removes that rail).
  const offers = repairOffers(projectRoot, hasLegacyCopies(projectRoot));
  for (const o of offers) outcome.trace.push(`repair-offered:${o.kind}`);
  if (offers.length > 0) sections.push({ title: '🔧 Repairs offered:', lines: offers.flatMap((o) => o.lines) });

  // 6b. The name contract (Req 5A; Task 6) — REPORT ONLY: the consumer's token
  //     tier is never written (5.8). Reads the package's compiled contract and her
  //     generated web CSS; no output → `cannot check`, never clean.
  outcome.nameContract = await nameContractSection(projectRoot, pkg.root, options.configLoader);
  sections.push({ title: '🔤 Name contract (your tokens vs. the names our components reference):', lines: outcome.nameContract.lines });

  // 6c. The type contract (DD11; Peter's fork-1 ruling (B), 2026-09-27). Only for a
  //     repo with a manifest. When the recorded hash differs, the PREVIOUS members come
  //     from the previously installed version's own contract, fetched through her rail.
  const installedContract = loadNameContractSafe(pkg.root)?.typeContract;
  if (persistManifest) {
    let typeFetcher: PackageFetcher | undefined;
    try {
      outcome.typeContract = assessTypeContract({
        recordedHash: manifest.contractHash,
        recordedVersion: manifest.installedVersion,
        current: installedContract,
        fetchPrevious: (version) => {
          typeFetcher = options.fetcher ?? npmRailFetcher(projectRoot);
          outcome.trace.push(`type-contract-fetch:${version}`);
          return previousContractAt(typeFetcher.fetch(version));
        },
      });
    } finally {
      typeFetcher?.dispose?.();
    }
    if (outcome.typeContract.lines.length > 0) sections.push({ title: '🧾 Type contract:', lines: outcome.typeContract.lines });
  }

  // 7. REPORT — always, before anything applies.
  const report = buildReport({ dryRun: Boolean(options.dryRun), manifestLines, files, keys: keyResults, sections });
  displayReport(report);
  outcome.report = report;
  await reportAndMaybeFixStaleSteeringDir(projectRoot, { dryRun: Boolean(options.dryRun) || !isTTY });

  // 8. Decide.
  if (options.dryRun) return { ...outcome, stopped: 'dry-run' };
  // Explicit per-repair flags are their own authorization (after the report).
  if (options.repairNpmrc && offers.some((o) => o.kind === 'npmrc') && repairRegistryPin(projectRoot)) {
    outcome.trace.push('repair-applied:npmrc');
    outcome.applied.push('.npmrc');
    console.log('  ✓ .npmrc: removed the @3fn → GitHub Packages mapping line');
  }
  if (options.repairTsconfig && offers.some((o) => o.kind === 'tsconfig') && repairTsconfigPins(projectRoot)) {
    outcome.trace.push('repair-applied:tsconfig');
    outcome.applied.push('tsconfig.test.json');
    console.log('  ✓ tsconfig.test.json: removed the raw-src @3fn/core paths entries');
  }
  if (options.migrateComponents && outcome.migration) {
    // The explicit flag IS the per-run authorization (nothing is removed without it).
    outcome.relocation = relocateComponents(projectRoot, outcome.migration);
    const r = outcome.relocation;
    console.log(
      `\n  ✓ --migrate-components: removed ${r.removed.length} unmodified cop${r.removed.length === 1 ? 'y' : 'ies'}, ` +
        `relocated ${r.relocated.length} to ${'src/components/<Name>/'}` +
        (r.skipped.length ? `; not moved (src/components/<Name>/ exists): ${r.skipped.join(', ')}` : '') +
        (r.leftInPlace.length ? `; left in place (cannot tell): ${r.leftInPlace.join(', ')}` : ''),
    );
  }
  if (options.migrateLegacy) {
    const ran = await runMigrateLegacy(projectRoot, pkg.root, manifest, outcome);
    if (ran) {
      // The attach step regenerated the agent layer and its MCP wiring: what was classified before it is
      // stale, so nothing else applies in this run. The manifest records exactly what attach wrote.
      manifest.installedVersion = pkg.version;
      if (installedContract) manifest.contractHash = installedContract.hash;
      outcome.manifestWritten = saveManifest(projectRoot, manifest);
      if (relocateLegacy && !legacyHasPointer(projectRoot)) writeLegacyPointer(projectRoot);
      console.log(`✅ Sync complete. ${MANIFEST_FILE} updated. Run 'npx designerpunk sync' again to review the migrated repo.`);
      console.log('');
      console.log(restartLineSequencedMessage());
      return outcome;
    }
  }
  const restore = new Set(options.restore ?? []);
  const overwrite = new Set(options.overwrite ?? []);
  const keyOf = (s: SurfaceKeyResult, key: string) => `${s.surface.file}#${key}`;

  const isRegion = (p: string) => p.endsWith('#managed');
  const fileBatch = [...files.new, ...files.updatedSafe].map((f) => f.relativePath);
  const fileRestore = files.deletedByYou.filter((f) => restore.has(f.relativePath)).map((f) => f.relativePath);
  // A region conflict is the catalog's "edited inside" row — "not applying without --apply": --apply (or
  // --overwrite <file>#managed) replaces it; the terminal's batch confirmation alone never does.
  const fileOverwrite = files.conflicts
    .filter((f) => overwrite.has(f.relativePath) || (isRegion(f.relativePath) && Boolean(options.apply)))
    .map((f) => f.relativePath);
  const keyWork = keyResults.map((s) => ({
    s,
    items: s.classified.filter(
      (c) =>
        c.classification === 'new' ||
        c.classification === 'updated-safe' ||
        (c.classification === 'deleted-by-you' && restore.has(keyOf(s, c.key))) ||
        (c.classification === 'conflict' && overwrite.has(keyOf(s, c.key))),
    ),
  }));
  const keyCount = keyWork.reduce((n, w) => n + w.items.length, 0);
  const manifestChanges =
    relocateLegacy ||
    pruned.length > 0 ||
    files.adoptable.length > 0 ||
    files.dropEntries.length > 0 ||
    keyResults.some((s) => s.dropEntries.length > 0) ||
    (persistManifest && manifest.installedVersion !== pkg.version) ||
    (persistManifest && installedContract !== undefined && manifest.contractHash !== installedContract.hash);
  const workCount = fileBatch.length + fileRestore.length + fileOverwrite.length + keyCount;
  if (workCount === 0 && !manifestChanges) return outcome;

  if (!options.apply) {
    if (!isTTY) {
      console.log(`\n${OFF_TTY_REPORT_ONLY_MESSAGE}`);
      return { ...outcome, stopped: 'off-tty' };
    }
    const confirm = options.confirm ?? terminalConfirm;
    const ok = await confirm(
      `\nApply ${workCount} change${workCount === 1 ? '' : 's'}${manifestChanges ? ' and update the manifest' : ''}?`,
    );
    if (!ok) {
      console.log('  ⏭ Nothing applied.');
      return { ...outcome, stopped: 'declined' };
    }
  }

  // 9. Apply — generated content from the package side computed above (never a package-file copy).
  const contents = new Map<string, string>([...(outcome.generated?.contents ?? new Map<string, string>()), ...gitignoreContents]);
  for (const rel of [...fileBatch, ...fileRestore, ...fileOverwrite]) {
    const content = contents.get(rel);
    if (content === undefined) continue;
    if (isRegion(rel) ? applyGeneratedRegion(projectRoot, rel, content, entries) : applyGeneratedFile(projectRoot, rel, content, entries)) {
      outcome.applied.push(rel);
    }
  }
  for (const f of files.adoptable) {
    const content = contents.get(f.relativePath);
    if (content === undefined) continue;
    entries[f.relativePath] = isRegion(f.relativePath)
      ? { hash: hashBuffer(normalizeRegionContent(content)), grain: 'region', origin: 'generated' }
      : { hash: hashBuffer(content), grain: 'file', origin: 'generated' };
  }
  for (const rel of files.dropEntries) delete entries[rel];
  for (const { s, items } of keyWork) {
    for (const id of s.dropEntries) delete entries[id];
    if (items.length === 0) continue;
    applyKeys(projectRoot, s.surface, items.map((c) => ({ key: c.key, value: c.packageValue })), entries);
    for (const c of items) outcome.applied.push(keyOf(s, c.key));
  }

  // 10. Save — the root manifest; relocation leaves the legacy file a pointer.
  if (persistManifest) {
    manifest.installedVersion = pkg.version;
    // Re-record the baseline AFTER the report, and only on this write (fork-1 ruling).
    if (installedContract) manifest.contractHash = installedContract.hash;
    outcome.manifestWritten = saveManifest(projectRoot, manifest);
    if (relocateLegacy && !legacyHasPointer(projectRoot)) writeLegacyPointer(projectRoot);
  }
  if (outcome.applied.length > 0) console.log(`\n  ✓ ${outcome.applied.length} change${outcome.applied.length === 1 ? '' : 's'} applied`);
  console.log(outcome.manifestWritten ? `✅ Sync complete. ${MANIFEST_FILE} updated.` : '✅ Sync complete.');
  return outcome;
}

const displayPath = (projectRoot: string, abs: string, dir = false): string => {
  const rel = path.relative(projectRoot, abs).split(path.sep).join('/');
  const shown = rel === '' ? '.' : rel.startsWith('..') ? abs : rel;
  return dir && !shown.endsWith('/') ? `${shown}/` : shown;
};

async function nameContractSection(
  projectRoot: string,
  pkgRoot: string,
  configLoader?: ConfigModuleLoader,
): Promise<NameContractResult | { status: 'cannot-check'; lines: string[] }> {
  const contract = loadNameContract(pkgRoot);
  if (!contract) return { status: 'cannot-check', lines: [contractMissingMessage(pkgRoot)] };
  let outputDir: string;
  let tokenRoot: string;
  try {
    const config = configLoader ? await loadConfig(projectRoot, configLoader) : await loadConfig(projectRoot);
    outputDir = config.outputDir;
    tokenRoot = config.tokenSourceMode === 'local' ? config.tokenSourceRoot : path.join(projectRoot, 'src', 'tokens');
  } catch (err) {
    return { status: 'cannot-check', lines: [configUnreadableMessage(err instanceof Error ? err.message : String(err))] };
  }
  return checkNameContract(contract, readPresentNames(outputDir), {
    outputDirDisplay: displayPath(projectRoot, outputDir),
    semanticTierPath: displayPath(projectRoot, path.join(tokenRoot, 'semantic'), true),
    primitiveTierPath: displayPath(projectRoot, tokenRoot, true),
  });
}

function loadNameContractSafe(pkgRoot: string): ReturnType<typeof loadNameContract> {
  try {
    return loadNameContract(pkgRoot);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Generated surfaces (Task 16.5; design.md § "C7" managed-set rows ADDED)
// ---------------------------------------------------------------------------

export function agentLayerUnavailableMessage(reason: string): string {
  return `could not generate DesignerPunk's agent layer from the installed package — ${reason}. Your generated agent files were not checked.`;
}

export interface GeneratedSurfaces {
  /** File grain (paths) and region grain (`<file>#managed` ids), classified together. */
  files: ClassificationResult;
  /** Package content by path / region id — what an apply writes. */
  contents: Map<string, string>;
  /** `untracked-new` items, with the target whose `attach` would record them (the catalog row names it). */
  untrackedNew: Array<{ path: string; target: string }>;
  /** Recorded regions whose markers are gone — the catalog's "markers missing" string; never written. */
  markersMissing: string[];
  /** The lane's Req 13 degradation warnings. */
  warnings: string[];
}

function markersFor(file: string) {
  return regionMarkers(file.endsWith('.md') ? CLAUDE_MD_COMMENT : GITIGNORE_COMMENT);
}

/**
 * The directories the package's agent layer writes into, derived from the emission itself (never a list
 * kept here): a path's first two segments (`.claude/agents`, `.kiro/steering`, `.claude/skills`, …). A
 * recorded generated entry under one of them that the package no longer emits is `removed`; a consumer's
 * own file there is never classified (it has no entry and no package counterpart).
 */
function agentLayerRoots(paths: string[]): string[] {
  const roots = new Set<string>();
  for (const p of paths) {
    const seg = p.split('/');
    roots.add(seg.length >= 3 ? seg.slice(0, 2).join('/') : seg.length === 2 ? seg[0] : p);
  }
  return [...roots].sort();
}

/**
 * Classify the generated surfaces for `targets` (the manifest's `attachedTargets` — C7: "the package side
 * of the generated surfaces is freshly generated, by `emitConsumer`, for the manifest's attachedTargets").
 * A target with nothing recorded yet yields `untracked-new` (reported, never applied); once `attach` has
 * recorded any of its surfaces, a newly emitted file is `new`.
 */
async function classifyGenerated(
  projectRoot: string,
  targets: readonly string[],
  emitFor: (target: string) => Promise<{ files: EmittedAgentFile[]; warnings: string[] }>,
  entries: Record<string, ManifestEntry>,
  ignore: IgnoreFilter,
): Promise<GeneratedSurfaces> {
  const contents = new Map<string, string>();
  const targetOf = new Map<string, string>();
  const pkgFiles: ScannedFile[] = [];
  const regions: Array<EmittedAgentFile & { target: string }> = [];
  const warnings: string[] = [];
  for (const target of targets) {
    const emitted = await emitFor(target);
    for (const w of emitted.warnings) if (!warnings.includes(w)) warnings.push(w);
    for (const f of emitted.files) {
      const id = f.grain === 'region' ? regionEntryId(f.path) : f.path;
      if (contents.has(id)) continue;
      contents.set(id, f.content);
      targetOf.set(id, target);
      if (f.grain === 'region') regions.push({ ...f, target });
      else pkgFiles.push({ relativePath: f.path, absolutePath: '', hash: hashBuffer(f.content) });
    }
  }
  const recordedTargets = new Set<string>();
  for (const [id, target] of targetOf) if (entries[id]?.origin === 'generated') recordedTargets.add(target);

  const roots = agentLayerRoots(pkgFiles.map((f) => f.relativePath));
  const files = classifyFiles(pkgFiles, scanFiles(projectRoot, roots), entries, ignore, roots, {
    origin: 'generated',
    untracked: (rel) => !recordedTargets.has(targetOf.get(rel) ?? ''),
  });

  const markersMissing: string[] = [];
  for (const r of regions) {
    if (ignore.isIgnored(r.path)) continue;
    const id = regionEntryId(r.path);
    const abs = path.join(projectRoot, r.path);
    const text = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf-8') : undefined;
    const entry = entries[id]?.origin === 'generated' && entries[id]?.grain === 'region' ? entries[id] : undefined;
    const c = classifyRegion(text, markersFor(r.path), r.content, entry, !recordedTargets.has(r.target));
    const item = (classification: ClassifiedFile['classification'], reason?: string): ClassifiedFile => ({
      relativePath: id,
      classification,
      packageHash: hashBuffer(normalizeRegionContent(r.content)),
      ...(entry ? { manifestHash: entry.hash } : {}),
      ...(reason ? { reason } : {}),
    });
    switch (c.kind) {
      case 'unchanged': files.unchanged.push(item('unchanged')); break;
      case 'updated-safe': files.updatedSafe.push(item('updated-safe', 'unchanged by you — package updated')); break;
      case 'conflict': files.conflicts.push(item('conflict', managedRegionEditedInsideMessage(r.path))); break;
      case 'new': files.new.push(item('new')); break;
      case 'untracked-new': files.untrackedNew.push(item('untracked-new')); break;
      case 'deleted-by-you': files.deletedByYou.push(item('deleted-by-you')); break;
      case 'adoptable': files.adoptable.push(item('unchanged')); break;
      case 'markers-missing': markersMissing.push(r.path); break;
    }
  }
  return {
    files,
    contents,
    untrackedNew: files.untrackedNew.map((f) => ({ path: f.relativePath, target: targetOf.get(f.relativePath) ?? '' })),
    markersMissing,
    warnings,
  };
}

/** Write one generated file and record exactly the bytes written (`origin: 'generated'`). */
function applyGeneratedFile(projectRoot: string, rel: string, content: string, entries: Record<string, ManifestEntry>): boolean {
  try {
    const abs = path.join(projectRoot, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf-8');
    entries[rel] = { hash: hashBuffer(content), grain: 'file', origin: 'generated' };
    return true;
  } catch (err) {
    console.error(`  ❌ Failed to apply ${rel}: ${(err as Error).message}`);
    return false;
  }
}

/**
 * Write one managed region (`<file>#managed`): splice it when the markers are there, create the file when it
 * is absent, append the region when the file has none (a `new` region — never a recorded one whose markers
 * she removed, which the classifier reports and never routes here). Outside bytes are never changed.
 */
function applyGeneratedRegion(projectRoot: string, id: string, content: string, entries: Record<string, ManifestEntry>): boolean {
  const file = id.slice(0, -'#managed'.length);
  const abs = path.join(projectRoot, file);
  const markers = markersFor(file);
  try {
    let text: string;
    if (!fs.existsSync(abs)) {
      text = wrapRegion(markers, content);
    } else {
      const existing = fs.readFileSync(abs, 'utf-8');
      const spliced = spliceRegion(existing, markers, content, file);
      text = spliced.ok ? spliced.text : appendRegion(existing, markers, content);
    }
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, text, 'utf-8');
    entries[id] = { hash: hashBuffer(normalizeRegionContent(content)), grain: 'region', origin: 'generated' };
    return true;
  } catch (err) {
    console.error(`  ❌ Failed to apply ${id}: ${(err as Error).message}`);
    return false;
  }
}

/**
 * The targets whose MCP keys `sync` reconciles: `attachedTargets`, plus any target the manifest records
 * keys for without attaching its agent layer (`init --skip-agents`; `attach --reference`, whose manifest
 * exists so `sync` can repair approval drift — DD22).
 */
function keyGrainTargets(manifest: DesignerPunkManifest): HarnessTarget[] {
  const targets = new Set<HarnessTarget>(manifest.attachedTargets);
  for (const surface of KEY_SURFACES) {
    if (Object.entries(manifest.entries).some(([id, e]) => e.grain === 'key' && id.startsWith(`${surface.file}#`))) targets.add(surface.target);
  }
  return [...targets];
}

/** A consume-posture manifest's package side: the reference servers only (C20 `--reference`; DD22). */
function restrictToReference(keys: Map<string, Map<string, unknown>>): void {
  for (const surfaceKeys of keys.values()) {
    for (const key of [...surfaceKeys.keys()]) {
      if (!REFERENCE_SERVERS.some((s) => key === s || key.startsWith(`mcp__${s}__`))) surfaceKeys.delete(key);
    }
  }
}

// ---------------------------------------------------------------------------
// --migrate-legacy (C7 Migration item 4; Task 16.5) — offered ONLY with attach,
// and run in the SAME flow: removal, then attach.
// ---------------------------------------------------------------------------

/**
 * Whether the attach step can run here — decided through `attach`'s own rules: the agent-layer lane loads
 * from the installed package, `attach` would not refuse this repo (born or package-mode only), every
 * requested target is declared, and the emission succeeds for each target it would attach.
 */
async function attachAvailability(
  projectRoot: string,
  manifest: DesignerPunkManifest,
  requested: readonly string[],
  agentLayer: AgentLayerSource | null,
  agentLayerReason: string,
  emitFor: (target: string) => Promise<unknown>,
): Promise<AttachAvailability> {
  if (!agentLayer) return { available: false, reason: agentLayerReason || 'the agent-layer lane is unavailable' };
  const refusal = attachRefusal(projectRoot);
  if (refusal.message !== null) return { available: false, reason: `attach refuses this repo: ${refusal.message}` };
  const declared = agentLayer.declaredTargets();
  const undeclared = requested.filter((t) => !declared.includes(t));
  if (undeclared.length > 0) {
    return { available: false, reason: `target ${undeclared.join(', ')} is not declared by the installed package (declared: ${declared.join(', ')})` };
  }
  const targets = [...new Set<string>([...manifest.attachedTargets, ...requested])];
  try {
    for (const t of targets) await emitFor(t);
  } catch (err) {
    return { available: false, reason: (err as Error).message };
  }
  return { available: true, targets, declared };
}

/**
 * `--migrate-legacy`: the removal, then — in the same run, through `attach`'s code path
 * (`emitAgentLayer`) — the attach step for each target. Refuses, removing nothing, when attach is not
 * available or there is no target. Returns true iff it ran.
 */
async function runMigrateLegacy(
  projectRoot: string,
  pkgRoot: string,
  manifest: DesignerPunkManifest,
  outcome: SyncOutcome,
): Promise<boolean> {
  if (!outcome.legacyCopies) {
    console.log('\n  --migrate-legacy: this manifest records no legacy copies — nothing to migrate.');
    return false;
  }
  const avail = outcome.attach;
  if (!avail || !avail.available) {
    outcome.trace.push('migrate-legacy:refused');
    console.log(`\n  ${migrateLegacyRefusedMessage(avail && !avail.available ? avail.reason : 'attach availability was not established')}`);
    return false;
  }
  if (avail.targets.length === 0) {
    outcome.trace.push('migrate-legacy:refused');
    console.log(`\n  ${migrateLegacyNeedsTargetMessage(avail.declared)}`);
    return false;
  }
  outcome.legacyRemoval = removeLegacyCopies(projectRoot, manifest.entries);
  outcome.trace.push(`migrate-legacy:removed:${outcome.legacyRemoval.removed.length}`);
  console.log(`\n${legacyRemovalSummary(outcome.legacyRemoval)}`);
  for (const target of avail.targets) {
    const layer = await emitAgentLayer({ pkgRoot, repoRoot: projectRoot, requestedTarget: target, mode: 'attach', manifest });
    outcome.trace.push(`attach:${target}`);
    outcome.applied.push(...layer.files);
    const parts = [`${layer.written} file${layer.written === 1 ? '' : 's'} written`];
    if (layer.unchanged > 0) parts.push(`${layer.unchanged} unchanged`);
    if (layer.collided > 0) parts.push(`${layer.collided} skipped (see warnings above)`);
    console.log(`  ✓ attached ${target} — ${parts.join(', ')}`);
  }
  return true;
}
