/**
 * `sync`'s report — and `sync`'s slice of the loud-failure catalog.
 *
 * Spec 123 Task 5.4 (design.md § "C7"; § "Error Handling — the loud-failure
 * catalog"). The report is ALWAYS printed before anything applies ("no class
 * applies without the report printing first"). Catalog rows are exact strings;
 * `sync.catalog.test.ts` pins each to its design row, string-equal.
 *
 * @see Spec 111 — Requirement 9; Spec 123 design.md § "C7"
 */

import type { ClassificationResult } from './Classifier';
import type { SurfaceKeyResult } from './KeyGrain';

// ---------------------------------------------------------------------------
// Catalog rows (design.md § "Error Handling") — exact strings
// ---------------------------------------------------------------------------

/** Row `deleted-by-you`. */
export function deletedByYouMessage(p: string): string {
  return `${p} was generated earlier and you deleted it — not re-adding. To restore: npx designerpunk sync --restore ${p}`;
}

/** Row `untracked-new`. */
export function untrackedNewMessage(p: string, target: string): string {
  return `${p} would be generated but was never recorded — not adding it on first sync. To add it: npx designerpunk attach --target=${target}`;
}

/** Row "consumer key under our prefix" (Leonardo A-R1) — info, once per key. */
export function yoursUnderPrefixMessage(key: string): string {
  return `${key} is under DesignerPunk's prefix but was not generated by DesignerPunk — it is yours; sync will not manage or remove it`;
}

// ---------------------------------------------------------------------------
// Strings authored at Task 5 (no catalog row exists) — pinned by the same test
// ---------------------------------------------------------------------------

/** The steward exemption (found-not-fixed item 5): sync never runs against the package's own tree. */
export const STEWARD_REPO_MESSAGE =
  "this is DesignerPunk's own source tree (the package root) — sync reconciles a consumer repo against its installed package, so there is nothing to sync here. Nothing was read or written.";

export const OFF_TTY_REPORT_ONLY_MESSAGE =
  'not a terminal and --apply was not given — reported only; nothing was changed. Re-run with --apply to apply the updates above.';

export const RETIRED_FORCE_MESSAGE =
  '--force / --accept-all are retired: updates apply with --apply (or one confirmation on a terminal); a conflict applies only with --overwrite <path>, and a file you deleted only with --restore <path>.';

export function corruptManifestMessage(error: string): string {
  return `designerpunk.manifest.json could not be read (${error}) — refusing to guess its baseline. Restore it from version control; nothing was changed.`;
}

export function invalidSurfaceMessage(file: string, error: string): string {
  return `${file} is not valid JSON (${error}) — not reading or rewriting it; DesignerPunk's keys in it were not checked.`;
}

export function packageKeysUnavailableMessage(reason: string): string {
  return `could not compute DesignerPunk's MCP keys from the installed package — ${reason}. Your MCP config files were not checked.`;
}

// ---------------------------------------------------------------------------
// Report assembly
// ---------------------------------------------------------------------------

export interface ReportModel {
  dryRun: boolean;
  /** Lines describing manifest relocation / pruning (Manifest.ts). */
  manifestLines: string[];
  files: ClassificationResult;
  keys: SurfaceKeyResult[];
  /** Additional sections (migration, repairs), already rendered. */
  sections: Array<{ title: string; lines: string[] }>;
}

export function buildReport(model: ReportModel): string[] {
  const out: string[] = [];
  const { files } = model;
  if (model.dryRun) out.push('🔍 Dry-run mode — no changes will be applied.', '');

  if (model.manifestLines.length > 0) {
    out.push('📋 Manifest:');
    for (const l of model.manifestLines) out.push(`   ${l}`);
    out.push('');
  }

  const keyItems = (cls: string) =>
    model.keys.flatMap((s) => s.classified.filter((c) => c.classification === cls).map((c) => `${s.surface.file}#${c.key}`));

  const newItems = [...files.new.map((f) => f.relativePath), ...keyItems('new')];
  const updated = [...files.updatedSafe.map((f) => f.relativePath), ...keyItems('updated-safe')];
  const conflicts = [
    ...files.conflicts.map((f) => `${f.relativePath} — ${f.reason}`),
    ...keyItems('conflict').map((k) => `${k} — you edited DesignerPunk's key`),
  ];
  const removed = [...files.removed.map((f) => f.relativePath), ...keyItems('removed')];
  const deleted = [...files.deletedByYou.map((f) => f.relativePath), ...keyItems('deleted-by-you')];
  const untracked = model.keys.flatMap((s) =>
    s.classified.filter((c) => c.classification === 'untracked-new').map((c) => ({ p: `${s.surface.file}#${c.key}`, t: s.surface.target })),
  );

  const group = (title: string, items: string[]) => {
    if (items.length === 0) return;
    out.push(`${title} (${items.length}):`);
    for (const i of items) out.push(`   ${i}`);
    out.push('');
  };
  group('📥 New from the package — applies after confirmation or --apply', newItems);
  group('🔄 Updated in the package, unchanged by you — applies after confirmation or --apply', updated);
  group('⚠️  Conflicts — never overwritten (per path: --overwrite <path>)', conflicts);
  group('⚠️  Removed from package (left in place)', removed);
  if (deleted.length > 0) {
    out.push(`🗑  Deleted by you (${deleted.length}):`);
    for (const p of deleted) out.push(`   ${deletedByYouMessage(p)}`);
    out.push('');
  }
  if (untracked.length > 0) {
    out.push(`➕ Never recorded (${untracked.length}):`);
    for (const u of untracked) out.push(`   ${untrackedNewMessage(u.p, u.t)}`);
    out.push('');
  }
  for (const s of model.keys) {
    if (s.invalid) out.push(`⚠️  ${invalidSurfaceMessage(s.surface.file, s.invalid)}`, '');
    for (const k of s.yoursUnderPrefix) out.push(`ℹ️  ${yoursUnderPrefixMessage(k)}`);
  }
  if (model.keys.some((s) => s.yoursUnderPrefix.length > 0)) out.push('');

  for (const section of model.sections) {
    if (section.lines.length === 0) continue;
    out.push(section.title);
    for (const l of section.lines) out.push(`   ${l}`);
    out.push('');
  }

  const unchangedCount = files.unchanged.length + model.keys.reduce((n, s) => n + s.classified.filter((c) => c.classification === 'unchanged').length, 0);
  if (unchangedCount > 0) out.push(`✓ ${unchangedCount} managed item${unchangedCount === 1 ? '' : 's'} unchanged`);
  if (newItems.length === 0 && updated.length === 0 && conflicts.length === 0) out.push('✅ Everything DesignerPunk manages is up to date.');
  return out;
}

export function displayReport(lines: string[]): void {
  for (const l of lines) console.log(l);
}
