import * as fs from 'fs';
const { splitFrontmatter } = require(process.cwd() + '/tools/agent-generator/frontmatter');
const { entryTree, partition } = require(process.cwd() + '/tools/agent-generator/partition');
const { hashText, hashEntry } = require(process.cwd() + '/tools/agent-generator/regrounding/hash');
const root = process.cwd() + '/';
const f = process.argv[2];
const { frontmatter, body } = splitFrontmatter(fs.readFileSync(root+f,'utf8'), f);
const units = partition(body).units.map(u => ({ anchor: u.anchor, text: u.text, hash: hashText(u.text) }));
const leaves = entryTree(frontmatter ?? {}).units.map(l => ({ path: l.path, value: l.value, hash: hashEntry(l.value) }));
fs.writeFileSync(process.argv[3], JSON.stringify({ source: f, units, leaves }, null, 1));
