/**
 * @category evergreen
 * @purpose Spec 123 Task 5 — `sync`'s catalog strings are string-EQUAL to their
 * design rows. Comparands transcribed verbatim from design.md § "Error Handling —
 * the loud-failure catalog (exact strings)" (six rows; the count is asserted),
 * plus the C7 step-3 phrase quoted in the design text.
 */

import { deletedByYouMessage, untrackedNewMessage, yoursUnderPrefixMessage } from '../sync/Reporter';
import { prunedMessage } from '../sync/Manifest';
import { modifiedCopiesMessage, cannotTellMessage, unmodifiedCopiesMessage } from '../sync/Migration';

const DESIGN_ROWS = {
  'migration — modified copies (Le-D1(3))': (n: number, names: string) =>
    `these ${n} modified copies now override the package's ${names} and will not receive updates. Keep them as your forks, or move them with 'sync --migrate-components' (relocates modified copies to src/components/<Name>/).`,
  'migration — cannot tell': (p: string, v: string) =>
    `cannot tell whether ${p} was modified — the package content for version ${v} could not be retrieved. Review before removing.`,
  'deleted-by-you': (p: string) =>
    `${p} was generated earlier and you deleted it — not re-adding. To restore: npx designerpunk sync --restore ${p}`,
  'untracked-new': (p: string, t: string) =>
    `${p} would be generated but was never recorded — not adding it on first sync. To add it: npx designerpunk attach --target=${t}`,
  'managed manifest pruned (D-B6)': (n: number, paths: string) =>
    `no longer managing ${n} files under ${paths} — under the current contract they are yours (not removed from disk)`,
  'consumer key under our prefix (Leonardo A-R1)': (k: string) =>
    `${k} is under DesignerPunk's prefix but was not generated by DesignerPunk — it is yours; sync will not manage or remove it`,
};

describe('sync — catalog string conformance', () => {
  test('exactly six catalog rows are covered', () => {
    expect(Object.keys(DESIGN_ROWS)).toHaveLength(6);
  });

  test('migration — modified copies', () => {
    expect(modifiedCopiesMessage(2, ['Button-Icon', 'Chip-Base'])).toBe(
      DESIGN_ROWS['migration — modified copies (Le-D1(3))'](2, 'Button-Icon, Chip-Base'),
    );
  });

  test('migration — cannot tell', () => {
    expect(cannotTellMessage('src/components/core/X/', '12.0.5')).toBe(
      DESIGN_ROWS['migration — cannot tell']('src/components/core/X/', '12.0.5'),
    );
  });

  test('deleted-by-you', () => {
    expect(deletedByYouMessage('.mcp.json#designerpunk-docs')).toBe(DESIGN_ROWS['deleted-by-you']('.mcp.json#designerpunk-docs'));
  });

  test('untracked-new', () => {
    expect(untrackedNewMessage('.mcp.json#designerpunk-docs', 'cc')).toBe(
      DESIGN_ROWS['untracked-new']('.mcp.json#designerpunk-docs', 'cc'),
    );
  });

  test('managed manifest pruned', () => {
    expect(prunedMessage(59, 'src/tokens')).toBe(DESIGN_ROWS['managed manifest pruned (D-B6)'](59, 'src/tokens'));
  });

  test('consumer key under our prefix', () => {
    expect(yoursUnderPrefixMessage('designerpunk-mine')).toBe(
      DESIGN_ROWS['consumer key under our prefix (Leonardo A-R1)']('designerpunk-mine'),
    );
  });

  test('C7 step 3 — the unmodified-copies line carries the design phrase verbatim', () => {
    expect(unmodifiedCopiesMessage(1, ['Chip-Base'])).toContain(
      'shadow package updates — remove them to receive updates (`sync --migrate-components`)',
    );
  });
});
