/**
 * @category evergreen
 * @purpose Spec 123 Task 5 — `sync`'s catalog strings are string-EQUAL to their
 * design rows. Comparands transcribed verbatim from design.md § "Error Handling —
 * the loud-failure catalog (exact strings)" (seven rows; the count is asserted),
 * plus the C7 step-3 phrase quoted in the design text.
 *
 * Erratum 2026-09-26 (Thurgood, completion/task-5-erratum-cannot-tell.md): the
 * "migration — cannot tell" row is THREE-CAUSE — its alternation
 * `<a|b|c>` is transcribed as CANNOT_TELL_REASONS, one comparand per cause —
 * and the new row "migration — cannot tell (remedy)" pins the remedy line.
 */

/** The erratum'd row's alternation, verbatim, one entry per cause. */
const CANNOT_TELL_REASONS = {
  'fetch-failed': (v: string) => `the package content for version ${v} could not be retrieved`,
  'transform-unrecoverable': (v: string) => `version ${v}'s copy transform cannot be recovered`,
  'version-unknown': () => 'the installed version is unknown',
};

import { deletedByYouMessage, untrackedNewMessage, yoursUnderPrefixMessage } from '../sync/Reporter';
import { prunedMessage } from '../sync/Manifest';
import { modifiedCopiesMessage, cannotTellMessage, cannotTellRemedyMessage, unmodifiedCopiesMessage } from '../sync/Migration';

const DESIGN_ROWS = {
  'migration — modified copies (Le-D1(3))': (n: number, names: string) =>
    `these ${n} modified copies now override the package's ${names} and will not receive updates. Keep them as your forks, or move them with 'sync --migrate-components' (relocates modified copies to src/components/<Name>/).`,
  'migration — cannot tell': (p: string, reason: string) =>
    `cannot tell whether ${p} was modified — ${reason}. Review before removing.`,
  'migration — cannot tell (remedy)': (names: string, itThem: 'it' | 'them') =>
    `sync cannot judge ${names}, so 'sync --migrate-components' leaves ${itThem} in src/components/core/. Decide each by hand: if you edited it, move it to src/components/<Name>/ (it becomes your fork); if you didn't, delete it and you'll get the package's version. Until then, the old core/ level keeps logging its legacy warning each time the component index loads.`,
  'deleted-by-you': (p: string) =>
    `${p} was generated earlier and you deleted it — not re-adding. To restore: npx designerpunk sync --restore ${p}`,
  'untracked-new': (p: string, t: string) =>
    `${p} would be generated but was never recorded — not adding it on first sync. To add it: npx designerpunk attach --target=${t}`,
  'managed manifest pruned (D-B6)': (n: number, paths: string) =>
    `no longer managing ${n} files under ${paths} — under the current contract they are yours (not removed from disk)`,
  'consumer key under our prefix (Leonardo A-R1)': (k: string) =>
    `${k} is under DesignerPunk's prefix but was not generated by DesignerPunk — it is yours; sync will not manage or remove it`,
};

describe('sync — catalog string conformance', () => {
  test('exactly seven catalog rows are covered, and the cannot-tell row has exactly three causes', () => {
    expect(Object.keys(DESIGN_ROWS)).toHaveLength(7);
    expect(Object.keys(CANNOT_TELL_REASONS)).toHaveLength(3);
  });

  test('migration — modified copies', () => {
    expect(modifiedCopiesMessage(2, ['Button-Icon', 'Chip-Base'])).toBe(
      DESIGN_ROWS['migration — modified copies (Le-D1(3))'](2, 'Button-Icon, Chip-Base'),
    );
  });

  test('migration — cannot tell — cause 1/3: offline / fetch failed', () => {
    expect(cannotTellMessage('src/components/core/X/', { kind: 'fetch-failed', version: '12.0.5' })).toBe(
      DESIGN_ROWS['migration — cannot tell']('src/components/core/X/', CANNOT_TELL_REASONS['fetch-failed']('12.0.5')),
    );
  });

  test('migration — cannot tell — cause 2/3: the 11.3–11.8 copy transform cannot be recovered', () => {
    expect(cannotTellMessage('src/components/core/X/a.ts', { kind: 'transform-unrecoverable', version: '11.3.0' })).toBe(
      DESIGN_ROWS['migration — cannot tell']('src/components/core/X/a.ts', CANNOT_TELL_REASONS['transform-unrecoverable']('11.3.0')),
    );
  });

  test('migration — cannot tell — cause 3/3: the installed version is unknown', () => {
    expect(cannotTellMessage('src/components/core/X/', { kind: 'version-unknown' })).toBe(
      DESIGN_ROWS['migration — cannot tell']('src/components/core/X/', CANNOT_TELL_REASONS['version-unknown']()),
    );
  });

  test('migration — cannot tell (remedy), singular and plural', () => {
    expect(cannotTellRemedyMessage(['Button-Icon'])).toBe(DESIGN_ROWS['migration — cannot tell (remedy)']('Button-Icon', 'it'));
    expect(cannotTellRemedyMessage(['Button-Icon', 'Chip-Base'])).toBe(
      DESIGN_ROWS['migration — cannot tell (remedy)']('Button-Icon, Chip-Base', 'them'),
    );
  });

  test('deleted-by-you', () => {
    expect(deletedByYouMessage('.mcp.json#designerpunk-docs')).toBe(DESIGN_ROWS['deleted-by-you']('.mcp.json#designerpunk-docs'));
  });

  test('untracked-new', () => {
    expect(untrackedNewMessage('.mcp.json#designerpunk-docs', 'cc')).toBe(
      DESIGN_ROWS['untracked-new']('.mcp.json#designerpunk-docs', 'cc'),
    );
  });

  test('managed manifest pruned', () => {
    expect(prunedMessage(59, 'src/tokens')).toBe(DESIGN_ROWS['managed manifest pruned (D-B6)'](59, 'src/tokens'));
  });

  test('consumer key under our prefix', () => {
    expect(yoursUnderPrefixMessage('designerpunk-mine')).toBe(
      DESIGN_ROWS['consumer key under our prefix (Leonardo A-R1)']('designerpunk-mine'),
    );
  });

  test('C7 step 3 — the unmodified-copies line carries the design phrase verbatim', () => {
    expect(unmodifiedCopiesMessage(1, ['Chip-Base'])).toContain(
      'shadow package updates — remove them to receive updates (`sync --migrate-components`)',
    );
  });
});
