#!/usr/bin/env tsx
/**
 * generate-legacy-path-manifest.ts — Legacy-Path Forwarding Manifest producer CLI.
 *
 * Spec 119-A, Task 3 (Thurgood / Docs-MCP infra). Thin CLI wrapper over the
 * testable producer core in `mcp-server/src/legacy-path/generate-manifest.ts`.
 *
 * Runs against the CURRENT pre-rename / pre-relocation tree and FREEZES the result
 * to a checked-in TS MODULE (`legacy-path-manifest.ts`, exporting
 * `FROZEN_LEGACY_MANIFEST`). This is a ONE-WAY GATE: after the Task 5 rename +
 * Task 6 relocation, the original `.kiro/steering/…` strings no longer exist on
 * disk and cannot be recovered — the frozen module is the only record. MUST be run
 * + checked in BEFORE Tasks 5/6.
 *
 * WHY TS, NOT JSON: the docs MCP runs from COMPILED output (tsc `dist/` +
 * esbuild bundle). A runtime `fs.readFileSync(__dirname/…json)` is NOT
 * copied/inlined by either toolchain, so a JSON artifact would be ABSENT from the
 * deployed server (silent loss of the legacy fallback). A TS const compiles +
 * inlines natively and survives `npm pack`.
 *
 *   npx tsx scripts/generate-legacy-path-manifest.ts
 *
 * Writes: mcp-server/src/legacy-path/legacy-path-manifest.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { buildLegacyPathManifest } from '../mcp-server/src/legacy-path/generate-manifest';
import { LegacyPathManifest } from '../mcp-server/src/models';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const OUT_PATH = path.join(
  PROJECT_ROOT,
  'mcp-server',
  'src',
  'legacy-path',
  'legacy-path-manifest.ts',
);

/**
 * Render the frozen manifest as a deterministic, sorted TS module. Entries are
 * already sorted by the producer core (localeCompare on legacyPath); we preserve
 * that order. `JSON.stringify(…, 2)` gives stable, sorted-key object output for
 * the `FROZEN_LEGACY_MANIFEST` literal.
 */
function renderModule(manifest: LegacyPathManifest): string {
  const body = JSON.stringify(manifest, null, 2);
  return `/**
 * FROZEN legacy-path forwarding manifest (Spec 119-A Task 3) — transition-only,
 * removable post-119-B sweep.
 *
 * Generated by \`scripts/generate-legacy-path-manifest.ts\` against the pre-rename /
 * pre-relocation tree, then FROZEN as a TS module. It is the only record of the
 * vanished \`.kiro/steering/…\` strings after Tasks 5/6 (they cannot be inferred by
 * scanning disk), so it must be supplied at runtime.
 *
 * WHY A TS MODULE (not the original checked-in JSON): the docs MCP runs from
 * COMPILED output — \`mcp-server/dist/index.js\` (tsc) and \`dist/mcp/docs-mcp.js\`
 * (esbuild \`--bundle\`). The old loader did \`fs.readFileSync(__dirname/…json)\`, a
 * runtime fs-read that NEITHER tsc NOR esbuild copies/inlines — so the manifest
 * was ABSENT from both compiled artifacts and the deployed MCP had no legacy
 * fallback (a false-green failure class). As a TS const it compiles under tsc and
 * inlines under esbuild natively, surviving \`npm pack\` with no fs-read /
 * \`__dirname\` / copy step.
 *
 * DO NOT hand-edit. Regenerate via the producer CLI (it emits this exact file).
 */
import { LegacyPathManifest } from '../models';

export const FROZEN_LEGACY_MANIFEST: LegacyPathManifest = ${body};
`;
}

function main(): void {
  const result = buildLegacyPathManifest(PROJECT_ROOT);

  fs.writeFileSync(OUT_PATH, renderModule(result.manifest), 'utf-8');

  console.log('Legacy-path manifest generated (FROZEN — one-way gate before Tasks 5/6).');
  console.log(`  Output: ${path.relative(PROJECT_ROOT, OUT_PATH)}`);
  console.log(`  Live distinct prompt refs (grep-extracted): ${result.promptRefCount}`);
  console.log('  Per-prompt extracted refs:');
  for (const [file, n] of Object.entries(result.perPrompt)) {
    console.log(`    ${file}: ${n}`);
  }
  console.log(`  Manifest entries (de-duped, real-doc targets only): ${result.manifest.entries.length}`);
  if (result.skipped.length > 0) {
    console.log(`  Skipped (no target doc — NOT emitted): ${result.skipped.length}`);
    for (const s of result.skipped) {
      console.log(`    - ${s.legacyPath}  [${s.reason}]`);
    }
  }
  // The producer core already asserts every legacyPath is `..`-free (throws otherwise).
  console.log('  ..-free assertion: PASSED (producer throws on any `..` key).');
}

main();
