#!/usr/bin/env tsx
/**
 * release-publish.ts — the hermetic publish path: ONE tarball, built in a fresh clone at the tag, checked, and
 * published unchanged to every registry.
 *
 * Law: ballot `.kiro/docs/ballots/2026-10-03-hermetic-publish-path.md` § 3.2 (RELEASE-FLOW step 5).
 * Record: `.kiro/issues/2026-10-01-in-repo-generate-output-contaminates-package-dist.md` (2026-10-03 sections).
 * Why it exists: 15.0.0 shipped two different artifacts under one version. The public-npm publish was built in a
 * working checkout, so 62 stale `dist/` files and MCP bundles resolved from gitignored nested `node_modules/`
 * shipped (Stacy's R-2). A fresh clone at the tag has neither. The script is the guard; the `prepublishOnly`
 * refusal of a folder publish is only the tripwire that sends the operator here.
 *
 * Usage (also `npm run release:publish -- <args>`):
 *   npx tsx scripts/release-publish.ts --dry-run <S>     RELEASE-FLOW 5.1: everything except the publish, in a
 *                                                        fresh clone at commit S (full or abbreviated SHA that
 *                                                        resolves in this checkout). Nothing is published.
 *   npx tsx scripts/release-publish.ts <version>         RELEASE-FLOW 5.3: the same, in a fresh clone at tag
 *                                                        v<version>, then publishes THAT tarball to GitHub
 *                                                        Packages and prints the public-npm command for 5.4.
 * Options:
 *   --source <git-url-or-path>   clone from here (default: this checkout's `origin` URL)
 *   --expect-sha <S>             publish mode: refuse unless v<version> resolves to S
 *   --keep                       keep the clone directory afterwards (for inspection)
 *
 * What it refuses (exit 1, nothing published):
 *   - the tag v<version> does not exist at the source, or does not resolve to --expect-sha;
 *   - publish mode: the tagged commit is not on this checkout's `origin/main` (fetch first);
 *   - publish mode: `npm whoami --registry=<GitHub Packages>` fails from this checkout (checked before any build);
 *   - the clone's HEAD is not the requested commit, or `package.json`'s version at that commit is not <version>;
 *   - the clone is not clean after checkout or after `npm ci`;
 *   - `npm ci`, `check:drift`, `npm pack` (scripts on: prepack builds) or `verify:token-index-clean` fails;
 *   - any `pack-assert` finding on the tarball (section 10: no leftovers, root-shape bundles, `themes: []`, ...).
 *
 * ORDER NOTE: `verify:token-index-clean` runs AFTER `npm pack`, not before it. The token index is regenerated by
 * the build, and the build runs inside pack's `prepack`; before the pack the check could only compare the committed
 * index with itself. `check:drift` reads committed files and runs before the pack. A tarball publish runs NO
 * lifecycle scripts (npm 10.9.3: `lib/commands/publish.js` and `libnpmpack` gate every script on
 * `spec.type === 'directory'`), so this script runs both checks itself.
 *
 * AUTH: the GitHub Packages publish runs with this checkout as its working directory, so npm reads this checkout's
 * gitignored `.npmrc` (or the user's npm config). The script never reads, copies or prints any npm config or token.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as crypto from 'crypto';
import { spawnSync } from 'child_process';
import { assertTarball, reportFindings, Finding } from './pack-assert';

const PROJECT_ROOT = path.resolve(__dirname, '..');

export const GH_REGISTRY = 'https://npm.pkg.github.com';
export const PUBLIC_REGISTRY = 'https://registry.npmjs.org';
export const PACKAGE_SCOPE = '@3fn';

// ─── Arguments ───────────────────────────────────────────────────────────────────────────────────

export type ReleaseArgs =
  | { mode: 'dry-run'; sha: string; source?: string; keep: boolean }
  | { mode: 'publish'; version: string; expectSha?: string; source?: string; keep: boolean };

const SHA_RE = /^[0-9a-f]{7,40}$/;
const VERSION_RE = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/;

export class Refusal extends Error {}

export function parseArgs(argv: string[]): ReleaseArgs {
  let dryRunSha: string | undefined;
  let version: string | undefined;
  let source: string | undefined;
  let expectSha: string | undefined;
  let keep = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const value = (flag: string): string => {
      const v = argv[++i];
      if (!v || v.startsWith('--')) throw new Refusal(`${flag} needs a value`);
      return v;
    };
    if (a === '--dry-run') dryRunSha = value('--dry-run');
    else if (a === '--source') source = value('--source');
    else if (a === '--expect-sha') expectSha = value('--expect-sha');
    else if (a === '--keep') keep = true;
    else if (a.startsWith('--')) throw new Refusal(`unknown option: ${a}`);
    else if (version === undefined) version = a.replace(/^v/, '');
    else throw new Refusal(`unexpected argument: ${a}`);
  }
  if (dryRunSha !== undefined) {
    if (version !== undefined) throw new Refusal('give either --dry-run <S> or <version>, not both');
    if (expectSha !== undefined) throw new Refusal('--expect-sha applies to a publish; a dry run already names its commit');
    if (!SHA_RE.test(dryRunSha)) throw new Refusal(`--dry-run needs a commit SHA (7–40 hex characters), got: ${dryRunSha}`);
    return { mode: 'dry-run', sha: dryRunSha, source, keep };
  }
  if (version === undefined) throw new Refusal('usage: release-publish.ts --dry-run <S> | <version> [--source <url>] [--expect-sha <S>] [--keep]');
  if (!VERSION_RE.test(version)) throw new Refusal(`not a version: ${version}`);
  if (expectSha !== undefined && !SHA_RE.test(expectSha)) throw new Refusal(`--expect-sha needs a commit SHA, got: ${expectSha}`);
  return { mode: 'publish', version, expectSha, source, keep };
}

// ─── Pure helpers ────────────────────────────────────────────────────────────────────────────────

/** The commit a tag names, from `git ls-remote <src> refs/tags/v<v> refs/tags/v<v>^{}`: the peeled line wins (annotated tag). */
export function parseLsRemote(output: string, tag: string): string | undefined {
  let direct: string | undefined;
  let peeled: string | undefined;
  for (const line of output.split('\n')) {
    const [sha, ref] = line.trim().split(/\s+/);
    if (!sha || !ref) continue;
    if (ref === `refs/tags/${tag}^{}`) peeled = sha;
    else if (ref === `refs/tags/${tag}`) direct = sha;
  }
  return peeled ?? direct;
}

/** POSIX single-quote a shell word when it needs it. */
export function shellQuote(word: string): string {
  return /^[A-Za-z0-9_@%+=:,./-]+$/.test(word) ? word : `'${word.replace(/'/g, `'\\''`)}'`;
}

export function ghPublishArgs(tarball: string): string[] {
  return ['publish', tarball, `--registry=${GH_REGISTRY}`, `--${PACKAGE_SCOPE}:registry=${GH_REGISTRY}`];
}

export function publicPublishArgs(tarball: string): string[] {
  return ['publish', tarball, `--registry=${PUBLIC_REGISTRY}`, `--${PACKAGE_SCOPE}:registry=${PUBLIC_REGISTRY}`, '--access', 'public'];
}

export function renderCommand(cmd: string, args: string[]): string {
  return [cmd, ...args].map(shellQuote).join(' ');
}

export function sha1OfFile(file: string): string {
  return crypto.createHash('sha1').update(fs.readFileSync(file)).digest('hex');
}

export interface ReleaseRecord {
  mode: 'dry-run' | 'publish';
  version: string;
  commit: string;
  source: string;
  tarball: string;
  sha1: string;
  fileCount: number;
  bytes: number;
  checks: { passed: number; total: number };
  publishedTo: string[];
  createdAt: string;
}

// ─── The run, with every side effect injected (so the unit tests can drive it) ─────────────────────

export interface RunResult {
  status: number;
  stdout: string;
}

export interface Deps {
  /** Runs a command. `inherit` streams its output to the operator (npm ci, pack, publish). */
  run(cmd: string, args: string[], cwd: string, inherit?: boolean): RunResult;
  mkdtemp(prefix: string): string;
  mkdir(dir: string): void;
  readFile(file: string): string;
  writeFile(file: string, text: string): void;
  listDir(dir: string): string[];
  fileSize(file: string): number;
  sha1(file: string): string;
  rm(dir: string): void;
  assertTarball(tgz: string, root: string): { findings: Finding[]; fileCount: number };
  log(line: string): void;
  now(): string;
}

export const realDeps: Deps = {
  run(cmd, args, cwd, inherit) {
    const r = spawnSync(cmd, args, { cwd, encoding: 'utf8', stdio: inherit ? 'inherit' : 'pipe', maxBuffer: 64 * 1024 * 1024 });
    return { status: r.status ?? 1, stdout: typeof r.stdout === 'string' ? r.stdout : '' };
  },
  mkdtemp: (prefix) => fs.mkdtempSync(path.join(os.tmpdir(), prefix)),
  mkdir: (d) => fs.mkdirSync(d, { recursive: true }),
  readFile: (f) => fs.readFileSync(f, 'utf8'),
  writeFile: (f, t) => fs.writeFileSync(f, t),
  listDir: (d) => fs.readdirSync(d),
  fileSize: (f) => fs.statSync(f).size,
  sha1: sha1OfFile,
  rm: (d) => fs.rmSync(d, { recursive: true, force: true }),
  assertTarball: (tgz, root) => assertTarball(tgz, root),
  log: (line) => console.log(line),
  now: () => new Date().toISOString(),
};

export interface RunOutcome {
  record: ReleaseRecord;
  recordPath: string;
  publicCommand: string;
}

export function runRelease(args: ReleaseArgs, deps: Deps, projectRoot: string = PROJECT_ROOT): RunOutcome {
  const must = (r: RunResult, what: string): string => {
    if (r.status !== 0) throw new Refusal(`${what} failed (exit ${r.status})`);
    return r.stdout;
  };
  const git = (cwd: string, ...a: string[]): RunResult => deps.run('git', a, cwd);

  const source = args.source ?? must(git(projectRoot, 'remote', 'get-url', 'origin'), 'git remote get-url origin').trim();

  // 1. The target commit.
  let target: string;
  let fetchRef: string;
  if (args.mode === 'publish') {
    const tag = `v${args.version}`;
    const ls = must(git(projectRoot, 'ls-remote', source, `refs/tags/${tag}`, `refs/tags/${tag}^{}`), `git ls-remote ${source}`);
    const commit = parseLsRemote(ls, tag);
    if (!commit) throw new Refusal(`tag ${tag} does not exist at ${source}. Tag S and push the tag first (RELEASE-FLOW 5.2).`);
    if (args.expectSha && !commit.startsWith(args.expectSha)) {
      throw new Refusal(`tag ${tag} resolves to ${commit}, not the expected ${args.expectSha}.`);
    }
    if (git(projectRoot, 'merge-base', '--is-ancestor', commit, 'origin/main').status !== 0) {
      throw new Refusal(`tag ${tag} (${commit}) is not on this checkout's origin/main. Run \`git fetch origin\` and check that the tag names the release squash S.`);
    }
    // Fail fast, before minutes of install and build: can this checkout's npm config publish to GitHub Packages?
    // `npm whoami` prints a user name, never a token. A worktree has no copy of the gitignored `.npmrc`.
    if (deps.run('npm', ['whoami', `--registry=${GH_REGISTRY}`], projectRoot).status !== 0) {
      throw new Refusal(`npm has no GitHub Packages auth from ${projectRoot} (\`npm whoami --registry=${GH_REGISTRY}\` failed). Run the script from the checkout whose npm config authenticates (the main checkout's gitignored .npmrc), not from a worktree.`);
    }
    target = commit;
    fetchRef = `refs/tags/${tag}`;
  } else {
    const full = git(projectRoot, 'rev-parse', '--verify', '--quiet', `${args.sha}^{commit}`);
    if (full.status !== 0) throw new Refusal(`${args.sha} is not a commit in this checkout. Run \`git fetch origin\` first.`);
    target = full.stdout.trim();
    fetchRef = target;
    if (git(projectRoot, 'merge-base', '--is-ancestor', target, 'origin/main').status !== 0) {
      deps.log(`WARNING: ${target} is not on this checkout's origin/main. A dry run there is allowed; a publish never is.`);
    }
  }

  // 2. A fresh clone at exactly that commit.
  const work = deps.mkdtemp('dp-release-');
  const clone = path.join(work, 'clone');
  const out = path.join(work, 'out');
  let succeeded = false;
  try {
    must(deps.run('git', ['init', '-q', clone], work), 'git init');
    deps.mkdir(out);
    must(git(clone, 'fetch', '-q', '--depth', '1', source, fetchRef), `git fetch ${fetchRef}`);
    must(git(clone, 'checkout', '-q', '--detach', 'FETCH_HEAD'), 'git checkout FETCH_HEAD');
    const head = must(git(clone, 'rev-parse', 'HEAD'), 'git rev-parse HEAD').trim();
    if (head !== target) throw new Refusal(`the clone is at ${head}, not the requested ${target}.`);

    const pkg = JSON.parse(deps.readFile(path.join(clone, 'package.json'))) as { name: string; version: string };
    if (args.mode === 'publish' && pkg.version !== args.version) {
      throw new Refusal(`package.json at v${args.version} says version ${pkg.version}: the tag and the version disagree.`);
    }
    deps.log(`release-publish: ${args.mode} of ${pkg.name}@${pkg.version} at ${target} (fresh clone of ${source})`);

    const assertClean = (when: string): void => {
      const st = must(git(clone, 'status', '--porcelain', '--untracked-files=all'), 'git status');
      if (st.trim() !== '') throw new Refusal(`the clone is not clean ${when}:\n${st}`);
    };
    assertClean('after checkout');

    // 3. Install from the root lock only; no nested installs exist in a fresh clone.
    must(deps.run('npm', ['ci', '--no-audit', '--no-fund'], clone, true), 'npm ci');
    assertClean('after npm ci');

    // 4. Pre-pack check that reads committed files.
    must(deps.run('npm', ['run', 'check:drift'], clone, true), 'npm run check:drift');

    // 5. Pack WITH lifecycle scripts: prepack builds.
    must(deps.run('npm', ['pack', '--pack-destination', out], clone, true), 'npm pack (scripts on)');
    const tgzs = deps.listDir(out).filter((f) => f.endsWith('.tgz'));
    if (tgzs.length !== 1) throw new Refusal(`expected exactly one tarball in ${out}, found ${tgzs.length}.`);
    const tarball = path.join(out, tgzs[0]);

    // 6. The token index the build regenerated must equal the committed one.
    must(deps.run('npm', ['run', 'verify:token-index-clean'], clone, true), 'npm run verify:token-index-clean');

    // 7. pack-assert on the tarball, against the tree it was built from.
    const assertion = deps.assertTarball(tarball, clone);
    const failedCount = reportFindings(assertion.findings);
    if (failedCount > 0) throw new Refusal(`pack-assert: ${failedCount} finding(s) on the tarball.`);

    // 8. The record: what the registries' sha1s must equal at RELEASE-FLOW step 6b.
    const record: ReleaseRecord = {
      mode: args.mode,
      version: pkg.version,
      commit: target,
      source,
      tarball,
      sha1: deps.sha1(tarball),
      fileCount: assertion.fileCount,
      bytes: deps.fileSize(tarball),
      checks: { passed: assertion.findings.filter((f) => f.ok).length, total: assertion.findings.length },
      publishedTo: [],
      createdAt: deps.now(),
    };
    const recordPath = path.join(out, 'release-publish-record.json');

    const ghCommand = renderCommand('npm', ghPublishArgs(tarball));
    const publicCommand = renderCommand('npm', publicPublishArgs(tarball));

    if (args.mode === 'publish') {
      // 9. GitHub Packages: this checkout's npm config authenticates; nothing is read or printed here.
      must(deps.run('npm', ghPublishArgs(tarball), projectRoot, true), 'npm publish to GitHub Packages');
      record.publishedTo.push(GH_REGISTRY);
    }
    deps.writeFile(recordPath, `${JSON.stringify(record, null, 2)}\n`);

    deps.log('');
    deps.log(`tarball:    ${tarball}`);
    deps.log(`sha1:       ${record.sha1}`);
    deps.log(`files:      ${record.fileCount}   bytes: ${record.bytes}   pack-assert: ${record.checks.passed}/${record.checks.total}`);
    deps.log(`record:     ${recordPath}`);
    if (args.mode === 'dry-run') {
      deps.log('');
      deps.log('DRY RUN — nothing was published. At 5.3, `release-publish.ts <version>` would run, from a fresh clone at the tag:');
      deps.log(`  ${ghCommand}`);
      deps.log('and hand this command over for 5.4:');
      deps.log(`  ${publicCommand}`);
    } else {
      deps.log('');
      deps.log(`Published to ${GH_REGISTRY}. RELEASE-FLOW 5.4 (Peter's terminal, web 2FA) — first check the file, then publish the SAME tarball:`);
      deps.log(`  shasum ${shellQuote(tarball)}    # must print ${record.sha1}`);
      deps.log(`  ${publicCommand}`);
      deps.log('Then RELEASE-FLOW step 6: both registries\' dist.shasum must equal the sha1 above.');
    }
    succeeded = true;
    return { record, recordPath, publicCommand };
  } finally {
    // On success the clone goes (unless --keep); the tarball and its record stay for 5.4 and step 6.
    // On a refusal everything stays, so the failure can be inspected.
    if (succeeded && !args.keep) deps.rm(clone);
    if (!succeeded) deps.log(`work dir kept for inspection: ${work}`);
  }
}

function main(): void {
  try {
    const args = parseArgs(process.argv.slice(2));
    runRelease(args, realDeps);
  } catch (e) {
    if (e instanceof Refusal) {
      console.error(`\nREFUSED: ${e.message}\nNothing was published.`);
      process.exit(1);
    }
    throw e;
  }
}

if (require.main === module) {
  main();
}
