/**
 * FROZEN legacy-path forwarding manifest (Spec 119-A Task 3) — transition-only,
 * removable post-119-B sweep.
 *
 * Generated by `scripts/generate-legacy-path-manifest.ts` against the pre-rename /
 * pre-relocation tree, then FROZEN as a TS module. It is the only record of the
 * vanished `.kiro/steering/…` strings after Tasks 5/6 (they cannot be inferred by
 * scanning disk), so it must be supplied at runtime.
 *
 * WHY A TS MODULE (not the original checked-in JSON): the docs MCP runs from
 * COMPILED output — `mcp-server/dist/index.js` (tsc) and `dist/mcp/docs-mcp.js`
 * (esbuild `--bundle`). The old loader did `fs.readFileSync(__dirname/…json)`, a
 * runtime fs-read that NEITHER tsc NOR esbuild copies/inlines — so the manifest
 * was ABSENT from both compiled artifacts and the deployed MCP had no legacy
 * fallback (a false-green failure class). As a TS const it compiles under tsc and
 * inlines under esbuild natively, surviving `npm pack` with no fs-read /
 * `__dirname` / copy step.
 *
 * DO NOT hand-edit. Regenerate via the producer CLI (it emits this exact file).
 */
import { LegacyPathManifest } from '../models';

export const FROZEN_LEGACY_MANIFEST: LegacyPathManifest = {
  generatedAt: '2026-06-29T14:50:35.261Z',
  transitionOnly: true,
  entries: [
    {
      legacyPath: '.kiro/steering/00-Steering Documentation Directional Priorities.md',
      id: 'steering-documentation-directional-priorities',
    },
    {
      legacyPath: '.kiro/steering/A Vision of the Future.md',
      id: 'a-vision-of-the-future',
    },
    {
      legacyPath: '.kiro/steering/Browser Distribution Guide.md',
      id: 'browser-distribution-guide',
    },
    {
      legacyPath: '.kiro/steering/Completion Documentation Guide.md',
      id: 'completion-documentation-guide',
    },
    {
      legacyPath: '.kiro/steering/Component-Development-Guide.md',
      id: 'component-development-guide',
    },
    {
      legacyPath: '.kiro/steering/Component-Inheritance-Structures.md',
      id: 'component-inheritance-structures',
    },
    {
      legacyPath: '.kiro/steering/Component-MCP-Document-Template.md',
      id: 'mcp-component-family-document-template',
    },
    {
      legacyPath: '.kiro/steering/component-meta-authoring-guide.md',
      id: 'component-meta-authoring-guide',
    },
    {
      legacyPath: '.kiro/steering/Component-Meta-Data-Shapes-Governance.md',
      id: 'component-meta-data-shapes-governance',
    },
    {
      legacyPath: '.kiro/steering/Component-Schema-Format.md',
      id: 'component-schema-format',
    },
    {
      legacyPath: '.kiro/steering/Component-Templates.md',
      id: 'component-family-templates',
    },
    {
      legacyPath: '.kiro/steering/Contract-System-Reference.md',
      id: 'contract-system-reference',
    },
    {
      legacyPath: '.kiro/steering/Core Goals.md',
      id: 'core-goals',
    },
    {
      legacyPath: '.kiro/steering/Cross-Platform vs Platform-Specific Decision Framework.md',
      id: 'cross-platform-vs-platform-specific-decision-framework',
    },
    {
      legacyPath: '.kiro/steering/DesignerPunk-Integration-Guide.md',
      id: 'designerpunk-integration-guide',
    },
    {
      legacyPath: '.kiro/steering/Personal Note.md',
      id: 'personal-note',
    },
    {
      legacyPath: '.kiro/steering/platform-implementation-guidelines.md',
      id: 'platform-implementation-guidelines',
    },
    {
      legacyPath: '.kiro/steering/Process-Cross-Reference-Standards.md',
      id: 'process-cross-reference-standards',
    },
    {
      legacyPath: '.kiro/steering/Process-Hook-Operations.md',
      id: 'process-hook-operations',
    },
    {
      legacyPath: '.kiro/steering/Process-Spec-Planning.md',
      id: 'process-spec-planning',
    },
    {
      legacyPath: '.kiro/steering/Process-Task-Type-Definitions.md',
      id: 'process-task-type-definitions',
    },
    {
      legacyPath: '.kiro/steering/Release Management System.md',
      id: 'release-management-system',
    },
    {
      legacyPath: '.kiro/steering/Rosetta-System-Architecture.md',
      id: 'rosetta-system-architecture',
    },
    {
      legacyPath: '.kiro/steering/rosetta-system-principles.md',
      id: 'rosetta-system-principles',
    },
    {
      legacyPath: '.kiro/steering/Start Up Tasks.md',
      id: 'start-up-tasks',
    },
    {
      legacyPath: '.kiro/steering/Technology Stack.md',
      id: 'technology-stack',
    },
    {
      legacyPath: '.kiro/steering/Test-Behavioral-Contract-Validation.md',
      id: 'test-behavioral-contract-validation',
    },
    {
      legacyPath: '.kiro/steering/Test-Development-Standards.md',
      id: 'test-development-standards',
    },
    {
      legacyPath: '.kiro/steering/Test-Failure-Audit-Methodology.md',
      id: 'test-failure-audit-methodology',
    },
    {
      legacyPath: '.kiro/steering/Token-Governance.md',
      id: 'token-governance',
    },
    {
      legacyPath: '.kiro/steering/Token-Quick-Reference.md',
      id: 'token-quick-reference',
    },
    {
      legacyPath: '.kiro/steering/Token-Resolution-Patterns.md',
      id: 'token-resolution-patterns',
    },
    {
      legacyPath: '.kiro/steering/Token-Semantic-Structure.md',
      id: 'token-semantic-structure',
    },
  ],
};
